fixx

diff --git a/archlinux b/archlinux
--- a/archlinux
+++ b/archlinux
@@ -5,19 +5,19 @@ archPath="/data/local/distro/arch"
 scriptSleep="10s"
 
 warning() {
-    echo -e  "[\033[33mWARNING\033[0m] - " "$1"
+    printf "[\033[33mWARNING\033[0m] - %s\n" "$1"
 }
 
 success() {
-    echo -e "[\033[32mSUCCESS\033[0m] - $1"
+    printf "[\033[32mSUCCESS\033[0m] - %s\n" "$1"
 }
 
 info() {
-    echo -e "[\033[34mINFO\033[0m] - $1"
+    printf "[\033[34mINFO\033[0m] - %s\n" "$1"
 }
 
 error() {
-    echo -e "[\033[31mERROR\033[0m] - $1" >&2
+    printf "[\033[31mERROR\033[0m] - %s\n" "$1" >&2
 }
 
 is_root() {
