update

diff --git a/archlinux b/archlinux
--- a/archlinux
+++ b/archlinux
@@ -181,11 +181,11 @@ is_arch_booted() {
 }
 
 boot_arch() {
+    arch_logo
     if is_arch_booted; then
         info "ArchLinux is already running"
         exit 0
     fi
-    arch_logo
     info "Booting ArchLinux"
     {
         sudo "$termuxBin/busybox" mount -o remount,dev,suid /data
@@ -204,22 +204,30 @@ boot_arch() {
 
 setup_root() {
     info "Setting up root account and updating your ArchLinux"
-    sudo "$termuxBin/busybox" chroot "$archPath" /bin/su - $user -c "\
-    pacman-key --init && \
-    pacman-key --populate archlinuxarm && \
-    pacman-key --refresh-keys && \
-    groupadd -g 3003 aid_inet && \
-    groupadd wheel && \
-    usermod -G 3003 -a root && \
-    sed -i 's/^# *%wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers && \
-    sudo sed -i 's/^#\(en_US\.UTF-8 UTF-8\)/\1/' /etc/locale.gen && \
-    echo "LANG=en_US.UTF-8" | tee /etc/locale.conf && \
-    locale-gen && \
-    pacman -Syu --noconfirm && \
-    pacman -S --noconfirm sudo && \
-    exit 0 || \
-    exit 1
-    "
+    if sudo "$termuxBin/busybox" chroot "$archPath" /bin/su - $user -c \
+    "(
+        groupadd -g 3003 aid_inet ||
+        true &&
+        groupadd wheel || true &&
+        usermod -G 3003 -a root &&
+        sed -i "s/^# \*%wheel ALL=\(ALL:ALL\) ALL/%wheel ALL=\(ALL:ALL\) ALL/" /etc/sudoers &&
+        sed -i "s/^#\\\(en_US\.UTF-8 UTF-8\\\)/\\1/" /etc/locale.gen &&
+        echo "LANG=en_US.UTF-8" > /etc/locale.conf &&
+        locale-gen &&
+        pacman-key --init &&
+        pacman-key --populate archlinuxarm &&
+        pacman-key --refresh-keys &&
+        pacman -Syu --noconfirm &&
+        pacman -S --noconfirm sudo &&
+        exit 0
+    ) || exit 1"; then
+        success "ArchLinux is now ready to use. You can login with \"archlinux login\""
+    else
+        error "Failed to setup ArchLinux enviroment"
+        exit 1
+    fi
+    warning "Please use \"archlinux login add username\" to add user"
+    info "To delete user you have to use userdel inside your ArchLinux"
 }
 
 login_arch() {
@@ -238,6 +246,7 @@ login_arch() {
 }
 
 shutdown_arch() {
+    arch_logo
     info "Shutting down ArchLinux"
     {
         sudo "$termuxBin/busybox" umount -l "$archPath/media/sdcard"
