fixed download logic

diff --git a/archlinux b/archlinux
--- a/archlinux
+++ b/archlinux
@@ -4,11 +4,11 @@ tmpPath="/data/local/tmp"
 archPath="/data/local/arch"
 
 warning() {
-    echo -e "[\033[31mWARNING\033[0m] - $1"
+    echo -e "[\033[33mWARNING\033[0m] - $1"
 }
 
 success() {
-    echo -e "[\033[33mSUCCESS\033[0m] - $1"
+    echo -e "[\033[32mSUCCESS\033[0m] - $1"
 }
 
 info(){
@@ -66,20 +66,15 @@ setup_env() {
 }
 
 download_zip() {
-    local zipPath="$1"
-    if [ -z "$zipPath" ]; then
-        warning "ArchLinux zip was not found"
-        info "Downloading ArchLinux Generic for aarch64(arm64)"
-        if sudo curl -L --progress-bar -o "$tmpPath/ArchLinuxARM-aarch64-latest.tar.gz" "http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz"; then
-            success "ArchLinux Generic ZIP was downloaded successfully"
-            info "File is located at $tmpPath/ArchLinuxARM-aarch64-latest.tar.gz"
-        else 
-            error "Unknown error while downloading ArchLinux Generic ZIP"
-            exit 1
-        fi
-        zipPath="$tmpPath/ArchLinuxARM-aarch64-latest.tar.gz"
+    warning "ArchLinux zip was not found"
+    info "Downloading ArchLinux Generic for aarch64(arm64)"
+    if sudo curl -L --progress-bar -o "$tmpPath/ArchLinuxARM-aarch64-latest.tar.gz" "http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz"; then
+        success "ArchLinux Generic ZIP was downloaded successfully"
+        info "File is located at $tmpPath/ArchLinuxARM-aarch64-latest.tar.gz"
+    else 
+        error "Unknown error while downloading ArchLinux Generic ZIP"
+        exit 1
     fi
-    echo "$zipPath"
 }
 
 redownload_zip() {
@@ -91,6 +86,9 @@ redownload_zip() {
 install_arch() {
     zipPath="$1"
 
+    if [ -z "$zipPath" ]; then
+        zipPath="$tmpPath/ArchLinuxARM-aarch64-latest.tar.gz"
+    fi
     info "Installing ArchLinux"
     if [ -d "$archPath" ]; then
         info "ArchLinux is already install on this device. If you want you can use \"reinstall\" option"
@@ -103,7 +101,7 @@ install_arch() {
         info "ArchLinux Generic ZIP was found at $tmpPath"
         info "If you want to redownload it use \"redownload\" option"
     else
-        download_zip "$1"
+        download_zip
     fi
     info "Unpacking ArchLinux Generic ZIP at $archPath"
     if sudo tar xvf "$zipPath" --numeric-owner -C "$archPath"; then
